### ISSUE TITLE
Misspelled word

### ISSUE THREAD

**Issue by fabriziotappero** [ortizdaniel/microflow#16]
in ExportUtils.java probably "estat" should be "state" in this line:
sb.append("\tstatic char estat = 0;\n").append(sep).append("\tswitch(estat) {").append(sep);

**Comment by ortizdaniel** [comment]
That was intentional as it is Catalan and not English. Translating that and some other parts fully to English is in progress.

**Comment by fabriziotappero** [comment]
Hola Daniel,
Thanks, that would be great.

Fabrizio

**Comment by ortizdaniel** [comment]
Translated and added multi-language support for the functions of an interface.

![interface_editor](https://user-images.githubusercontent.com/5923590/56083365-21c67a80-5e24-11e9-9226-ab5edad25e80.jpeg)
