### ISSUE TITLE
Els scrolls (horitzontal i vertical) no funcionen.

### ISSUE THREAD

**Issue by FerranMontoliu** [ortizdaniel/microflow#17]
Els scrolls no funcionen en Windows 10.
Testejat en 3 dispositius diferents.

**Comment by ortizdaniel** [comment]
Para que el scroll funcione tienes que tener un un canvas de tamaño superior al que cabe en el programa. En el menú superior, ve a "Window" -> "Change size" e incrementa el tamaño del canvas, entonces el scroll se activará.
