### ISSUE TITLE
GUI scroll problem

### ISSUE THREAD

**Issue by fabriziotappero** [ortizdaniel/microflow#19]
When a graph is made on a large screen and the same graph open on a smaller screen, there is no way to scroll down. It would be necessary to turn on vertical scolling.
See attached file.
![2019-04-22_16-21](https://user-images.githubusercontent.com/8971950/56505031-c3338780-651a-11e9-8088-8de49ee1d441.png)

**Comment by ortizdaniel** [comment]
Sounds right (due to the way it's programmed right now).

As of now, you can go to "Window -> Change size" and increase the height of the canvas to be able to scroll to those elements that are off-screen.

Will fix.

**Comment by fabriziotappero** [comment]
yeah, I did actually managed to recover the work with your suggestion. It would be great to have the scroll bar to appear as the design gets bigger than the page. Cheers

**Comment by ortizdaniel** [comment]
Fixed. Check the [v1.6.4](https://github.com/ortizdaniel/microflow/releases/tag/v1.6.4) release.
