### ISSUE TITLE
open file does not remember history

### ISSUE THREAD

**Issue by fabriziotappero** [ortizdaniel/microflow#20]
When a project file is opened via the File - Open File path, the program does not remember the last location visited. This makes the use of this program quite hard since every time a file is opened, it is necessary to navigate through the HD.

**Comment by ortizdaniel** [comment]
Will look into this.

**Comment by fabriziotappero** [comment]
It actually remember it in certain conditions but most of the time does not. 

I wish you had made this in python instead of java. I could have helped.

**Comment by fabriziotappero** [comment]
hope you can fix it in the next release.

**Comment by ortizdaniel** [comment]
_Should be_ fixed. Check the [v1.6.4](https://github.com/ortizdaniel/microflow/releases/tag/v1.6.4) release.
