### ISSUE TITLE
text is wrongly autoformatted

### ISSUE THREAD

**Issue by fabriziotappero** [ortizdaniel/microflow#26]
When a graph is created, the text for a state condition has a font size that seems to depend on the length of the condition. This results in a not so good visual rappresentation of the graph. maybe font size should be fixed?

Example in attachment

![Captura11](https://user-images.githubusercontent.com/8971950/57780727-23d46f80-7729-11e9-8fc7-8c6a4a5074fc.PNG)

**Comment by ortizdaniel** [comment]
This is intentional as sometimes (in class exercises mostly) people have really long conditions, e.g., someVariable == CONSTANT && TiGetTicks(t) > TEN_MS. This was added to aid in this aspect and reduce the amount of space used.

**Comment by fabriziotappero** [comment]
Hi,
yeah, I understand. The problem I see is not the small text is too small but that the bit text (like "finished()") is too bit. Wouldn't be a good idea to have all text the same size as "setBeginSMS()"?
thanks
